### ISSUE TITLE
Script Failed 14.2 openelec 5.0.8

### ISSUE THREAD

**Issue by a1danslat3** [Backflipz/plugin.video.excubed#1]
Hi mate when I try to launch the add-on I get script failed. I have never use XDCC grabber before so not sure about configuration settings. Is there any forum where this is being discussed ? 

Looks like a great add-on and would love to try it out. 

I can send you log if you would like ?

**Comment by Backflipz** [comment]
Ah, it was a dumb mistake most likely. This is my first add-on and first time on github, I uploaded a zip with the incorrect structure. It should be fixed now on the releases page. I've just created a forum post at http://forum.kodi.tv/showthread.php?tid=228437

**Comment by a1danslat3** [comment]
No Worries mate. Delighted that you got back to me. You have a lot of talent.
